### ISSUE TITLE
Quick Transfer filenames end with _

### ISSUE THREAD

**Issue by finnless** [HMC-Makerspace/MAKE#13]
Seems to be some sort of issue with: https://github.com/HMC-Makerspace/MAKE/blob/3159c805b9dd000ea8d02ff520105dce2b9618f9/MAKE-website/scripts/page_home.js#L203-L232

Filenames always end with _ after the file extension after downloading through the UI.

I'm able to download from download_route without issue.

https://github.com/HMC-Makerspace/MAKE/blob/3159c805b9dd000ea8d02ff520105dce2b9618f9/MAKE-server/routes/routes_users.py#L392-L418

**Comment by IonImpulse** [comment]
I refactored the function in 8707d17, let me know if this fixes it for you!

**Comment by finnless** [comment]
Working great now, thanks!
