### ISSUE TITLE
Save past steward schedules in management console

### ISSUE THREAD

**Issue by git-wil** [HMC-Makerspace/MAKE#25]

**Comment by IonImpulse** [comment]
There are several issues with how this works currently. First, it appears to loop through and try to get the information for every single steward. This is very, very slow and we already have the info in `state.users`. Additionally, the request are the full names of the stewards, not the UUIDs, so the requests all fail.

![Image](https://github.com/user-attachments/assets/8715a4f9-0073-476c-8486-23d0a46c89e2)

**Comment by git-wil** [comment]
Closed with #74
