### ISSUE TITLE
Search by shelf on Inventory 

### ISSUE THREAD

**Issue by buffeinstein** [HMC-Makerspace/MAKE#40]
I wanted to be able to figure out what the giant role of cotton was called (its 'Cotton Battening). I figured out what it was by going to the Inventory kiosk and selecting 'The Cage' in '--Select Room/Area` and scrolling through what all is supposed to be in shelf 4. I realized it would be nice if I could search by 'Cage 4A' or of even  `Cmd+F` for '4A' because I can't see up there. I can imagine this would also be super helpful in being able to check shelf-by-shelf for inventory on what might be missing or to figure out what something is, instead of searching by item/guessing_keywords and seeing if its in the wrong spot. Let me know if I'm just not using the pre-existing search tools correctly!

**Comment by git-wil** [comment]
Hi, this feature does already exist!
The second search box after the area is for searching through the container/specific location of an item, which includes its shelf number, cabinet number, room, etc. The search box is shown highlighted below:

![image](https://github.com/user-attachments/assets/41b0d231-8e81-4545-94ee-609923e6409d)
